name: CI

on:
  push:
    branches:
    - master

jobs:
  build:
    name: Deploy website
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Deploying to github page
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        npm install
        npm run deploy
